// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2007-11-8 17:33:07 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files\Lassalle Technologies\AddFlow 5\AddFlow5.ocx (1)
// LIBID: {DE173711-6CFE-432E-A95E-F4EF3EE03231}
// LCID: 0
// Helpfile: C:\Program Files\Lassalle Technologies\AddFlow 5\AddFlow5.chm
// HelpString: Lassalle AddFlow 5 ActiveX Control version
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINDOWS\system32\stdole2.tlb)
// ************************************************************************ //
#ifndef   AddFlow5Lib_OCXH
#define   AddFlow5Lib_OCXH

#pragma option push -b -w-inl

#include <olectrls.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "AddFlow5Lib_TLB.h"
namespace Addflow5lib_tlb
{

// *********************************************************************//
// HelpString: Lassalle AddFlow 5 ActiveX Control version
// Version:    5.4
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TAddFlow
// Help String      : Lassalle AddFlow 5 ActiveX Control
// Default Interface: _DAddFlow
// Def. Intf. Object: _DAddFlowDisp
// Def. Intf. DISP? : Yes
// Event   Interface: _DAddFlowEvents
// TypeFlags        : (38) CanCreate Licensed Control
// *********************************************************************//

// *********************************************************************//
// Definition of closures to allow VCL handlers to catch OCX events.      
// *********************************************************************//
typedef void __fastcall (__closure * TAddFlowError)(System::TObject * Sender, 
                                                    short Number, BSTR* Description, long Scode, 
                                                    BSTR Source, BSTR HelpFile, long HelpContext, 
                                                    VARIANT_BOOL* CancelDisplay);
typedef void __fastcall (__closure * TAddFlowAfterAddNode)(System::TObject * Sender, 
                                                           Addflow5lib_tlb::afNode* NewNode);
typedef void __fastcall (__closure * TAddFlowAfterAddLink)(System::TObject * Sender, 
                                                           Addflow5lib_tlb::afLink* NewLink);
typedef void __fastcall (__closure * TAddFlowBeforeAddNode)(System::TObject * Sender, 
                                                            float Left, float Top, float Width, 
                                                            float Height, short* Cancel);
typedef void __fastcall (__closure * TAddFlowBeforeAddLink)(System::TObject * Sender, 
                                                            Addflow5lib_tlb::afNode* Org, 
                                                            Addflow5lib_tlb::afNode* Dst, 
                                                            short* Cancel);
typedef void __fastcall (__closure * TAddFlowBeforeEdit)(System::TObject * Sender, 
                                                         Addflow5lib_tlb::afNode* node, 
                                                         short* Cancel);
typedef void __fastcall (__closure * TAddFlowAfterEdit)(System::TObject * Sender, 
                                                        Addflow5lib_tlb::afNode* node, short* Cancel, 
                                                        BSTR* NewString);
typedef void __fastcall (__closure * TAddFlowBeforeChangeDst)(System::TObject * Sender, 
                                                              Addflow5lib_tlb::afLink* link, 
                                                              Addflow5lib_tlb::afNode* Dst, 
                                                              short* Cancel);
typedef void __fastcall (__closure * TAddFlowBeforeChangeOrg)(System::TObject * Sender, 
                                                              Addflow5lib_tlb::afLink* link, 
                                                              Addflow5lib_tlb::afNode* Org, 
                                                              short* Cancel);
typedef void __fastcall (__closure * TAddFlowNodeOwnerDraw)(System::TObject * Sender, 
                                                            long Hdc, Addflow5lib_tlb::afNode* node, 
                                                            long* Flags);
typedef void __fastcall (__closure * TAddFlowLinkOwnerDraw)(System::TObject * Sender, 
                                                            long Hdc, Addflow5lib_tlb::afLink* link, 
                                                            long* Flags);
typedef void __fastcall (__closure * TAddFlowDiagramOwnerDraw)(System::TObject * Sender, 
                                                               long Hdc, long* Flags);
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
// Proxy class to host Lassalle AddFlow 5 ActiveX Control in CBuilder IDE/Applications.
//-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
class PACKAGE TAddFlow : public TOleControl
{
  OVERLOADED_PROP_METHODS;
  static TNoParam  OptParam;
  static GUID      DEF_CTL_INTF;

  // Instance of Closures to expose OCX Events as VCL ones
  //
  TAddFlowError                  FOnError;
  TNotifyEvent                   FOnScroll;
  TNotifyEvent                   FOnafLostFocus;
  TNotifyEvent                   FOnafGotFocus;
  TAddFlowAfterAddNode           FOnAfterAddNode;
  TAddFlowAfterAddLink           FOnAfterAddLink;
  TAddFlowBeforeAddNode          FOnBeforeAddNode;
  TAddFlowBeforeAddLink          FOnBeforeAddLink;
  TNotifyEvent                   FOnAfterResize;
  TNotifyEvent                   FOnAfterMove;
  TNotifyEvent                   FOnAfterStretch;
  TNotifyEvent                   FOnAfterSelect;
  TAddFlowBeforeEdit             FOnBeforeEdit;
  TAddFlowAfterEdit              FOnAfterEdit;
  TAddFlowBeforeChangeDst        FOnBeforeChangeDst;
  TAddFlowBeforeChangeOrg        FOnBeforeChangeOrg;
  TAddFlowNodeOwnerDraw          FOnNodeOwnerDraw;
  TAddFlowLinkOwnerDraw          FOnLinkOwnerDraw;
  TAddFlowDiagramOwnerDraw       FOnDiagramOwnerDraw;

  // Default Interace of OCX
  //
  _DAddFlowDisp m_OCXIntf;

  // VCL Property Getters/Setters which delegate to OCX
  //
  Addflow5lib_tlb::afLink* __fastcall get_PointedLink();
  void __fastcall set_PointedLink(Addflow5lib_tlb::afLink* param);
  Addflow5lib_tlb::afSelLinks* __fastcall get_SelLinks();
  void __fastcall set_SelLinks(Addflow5lib_tlb::afSelLinks* param);
  Addflow5lib_tlb::afSelNodes* __fastcall get_SelNodes();
  void __fastcall set_SelNodes(Addflow5lib_tlb::afSelNodes* param);
  Addflow5lib_tlb::afPictures* __fastcall get_Pictures();
  void __fastcall set_Pictures(Addflow5lib_tlb::afPictures* param);
  Addflow5lib_tlb::afNode* __fastcall get_RedoNode();
  void __fastcall set_RedoNode(Addflow5lib_tlb::afNode* param);
  Addflow5lib_tlb::afLink* __fastcall get_RedoLink();
  void __fastcall set_RedoLink(Addflow5lib_tlb::afLink* param);
  Addflow5lib_tlb::afLink* __fastcall get_UndoLink();
  void __fastcall set_UndoLink(Addflow5lib_tlb::afLink* param);
  Addflow5lib_tlb::afNodes* __fastcall get_Nodes();
  void __fastcall set_Nodes(Addflow5lib_tlb::afNodes* param);
  Addflow5lib_tlb::afNode* __fastcall get_SelectedNode();
  void __fastcall set_SelectedNode(Addflow5lib_tlb::afNode* param);
  Addflow5lib_tlb::afNode* __fastcall get_PointedNode();
  void __fastcall set_PointedNode(Addflow5lib_tlb::afNode* param);
  Addflow5lib_tlb::afLink* __fastcall get_SelectedLink();
  void __fastcall set_SelectedLink(Addflow5lib_tlb::afLink* param);
  Addflow5lib_tlb::afCustomShapes* __fastcall get_CustomShapes();
  void __fastcall set_CustomShapes(Addflow5lib_tlb::afCustomShapes* param);
  Addflow5lib_tlb::afNode* __fastcall get_UndoNode();
  void __fastcall set_UndoNode(Addflow5lib_tlb::afNode* param);

  // Static variables used by all instances of OCX proxy
  //
  static int          EventDispIDs[19];
  static WCHAR        wLicenseKey[11];
  static int          TFontIDs[1];
  static int          TPictureIDs[2];
  static TControlData CControlData;
  static GUID         CTL_DEF_INTF;

  // Method providing access to interface as __property 
  //
  _DAddFlowDisp __fastcall GetDefaultInterface();
  _DAddFlowDisp __fastcall GetControlInterface()
  { return GetDefaultInterface(); }

protected:
  void     __fastcall CreateControl  ();
  void     __fastcall InitControlData();

public:
  virtual  __fastcall TAddFlow(TComponent* AOwner) : TOleControl(AOwner)
  {};
  virtual  __fastcall TAddFlow(HWND        Parent) : TOleControl(Parent)
  {};

  // OCX methods
  //
  void            __fastcall AboutBox(void);
  Addflow5lib_tlb::afLink* __fastcall AddLink(Addflow5lib_tlb::afNode* Org, 
                                              Addflow5lib_tlb::afNode* Dst);
  IPictureDisp**  __fastcall ExportPagePicture(float Left, float Top, float Width, float Height);
  OLE_HANDLE      __fastcall SaveMemory(Addflow5lib_tlb::ItemSetConstants ItemSet);
  void            __fastcall LoadMemory(OLE_HANDLE hMem);
  void            __fastcall BeginAction(short code);
  void            __fastcall UndocMethod(short param);
  void            __fastcall EndAction(void);
  VARIANT_BOOL    __fastcall CanRedo(void);
  VARIANT_BOOL    __fastcall CanUndo(void);
  void            __fastcall Redo(void);
  void            __fastcall Undo(void);
  void            __fastcall ZoomRectangle(short TypeZoom, float Left, float Top, float Width, 
                                           float Height);
  void            __fastcall SelectRectangle(Addflow5lib_tlb::FilterConstants Filter, float Left, 
                                             float Top, float Width, float Height);
  void            __fastcall StartEdit(void);
  VARIANT_BOOL    __fastcall CanPaste(void);
  void            __fastcall Paste(VARIANT_BOOL SelectPastedItems);
  void            __fastcall Copy(Addflow5lib_tlb::ItemSetConstants ItemSet);
  void            __fastcall DisplayPropertyPage(short param);
  IPictureDisp**  __fastcall ExportPicture(Addflow5lib_tlb::ItemSetConstants ItemSet, 
                                           VARIANT_BOOL IncludeBackColor, 
                                           VARIANT_BOOL IncludeBackPic);
  Addflow5lib_tlb::afLink* __fastcall GetLinkAtPoint(float x, float y);
  Addflow5lib_tlb::afNode* __fastcall GetNodeAtPoint(float x, float y);
  void            __fastcall LoadFile(BSTR file);
  void            __fastcall SaveFile(BSTR file);
  void            __fastcall DeleteMarked(void);
  void            __fastcall DeleteSel(void);
  void            __fastcall GetVersion(short* major, short* minor);
  void            __fastcall SetSelChangedFlag(VARIANT_BOOL SelChanged);
  VARIANT_BOOL    __fastcall IsSelChanged(void);
  void            __fastcall SaveImage(Addflow5lib_tlb::SaveImageMediumConstants tymed, 
                                       Addflow5lib_tlb::SaveImageFormatConstants format, BSTR file);
  void            __fastcall DoClick(void);
  void            __fastcall SetChangedFlag(VARIANT_BOOL Changed);
  VARIANT_BOOL    __fastcall IsChanged(void);
  void            __fastcall SelectAll(void);
  void            __fastcall Refresh(void);

  // OCX properties
  //
  __property _DAddFlowDisp ControlInterface={ read=GetDefaultInterface };

  // Published properties
  //
__published:

  // Standard/Extended properties
  //
  __property ParentColor;
  __property ParentFont;
  __property TabStop;
  __property Align;
  __property DragCursor;
  __property DragMode;
  __property ParentShowHint;
  __property PopupMenu;
  __property ShowHint;
  __property TabOrder;
  __property Visible;
  __property OnDragDrop;
  __property OnDragOver;
  __property OnEndDrag;
  __property OnEnter;
  __property OnExit;
  __property OnStartDrag;
  __property OnMouseUp;
  __property OnMouseMove;
  __property OnMouseDown;
  __property OnKeyUp;
  __property OnKeyPress;
  __property OnKeyDown;
  __property OnDblClick;
  __property OnClick;

  // OCX properties
  //
public:  /* !__published] */
  __property Graphics::TPicture * BackPicture={ read=GetTPictureProp, write=SetTPictureProp, stored=false, index=66 };
__published:
  __property bool Repaint={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=68 };
  __property Activex::TOleEnum ArrowOrg={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=72 };
  __property Activex::TOleEnum PointedArea={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=64 };
  __property bool Enabled={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=-514 };
  __property int hWnd={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=-515 };
  __property Activex::TOleEnum Alignment={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=65 };
  __property Activex::TOleEnum ShapeOrientation={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=89 };
  __property bool ReadOnly={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=35 };
  __property bool DisplayHandles={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=34 };
  __property bool MultiSel={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=36 };
  __property Activex::TOleEnum SelectAction={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=91 };
  __property int StretchingPoint={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=88 };
  __property Activex::TOleEnum ArrowMid={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=90 };
  __property bool ProportionalBars={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=92 };
  __property Graphics::TColor BackColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=-501 };
  __property bool CanDrawNode={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=1 };
  __property Activex::TOleEnum DrawStyle={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=61 };
  __property float yScroll={ read=GetSingleProp, write=SetSingleProp, stored=false, index=63 };
  __property bool CanMoveNode={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=2 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afLinkPtr PointedLink={ read=get_PointedLink, stored=false };
__published:
  __property Graphics::TFont * Font={ read=GetTFontProp, write=SetTFontProp, stored=false, index=-512 };
  __property Activex::TOleEnum LinkStyle={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=82 };
  __property float xScroll={ read=GetSingleProp, write=SetSingleProp, stored=false, index=62 };
  __property Activex::TOleEnum Shape={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=59 };
  __property bool AutoScroll={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=3 };
  __property Activex::TOleEnum AutoSize={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=69 };
  __property Activex::TOleEnum ScrollBars={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=60 };
  __property float yGrid={ read=GetSingleProp, write=SetSingleProp, stored=false, index=57 };
  __property float xGrid={ read=GetSingleProp, write=SetSingleProp, stored=false, index=56 };
  __property bool SelectMode={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=58 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afSelLinksPtr SelLinks={ read=get_SelLinks, stored=false };
__published:
  __property Graphics::TColor GridColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=23 };
  __property Graphics::TColor ForeColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=30 };
  __property Graphics::TColor FillColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=29 };
  __property bool ShowGrid={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=24 };
  __property Activex::TOleEnum LinkCreationMode={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=21 };
  __property Activex::TOleEnum PicturePosition={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=85 };
  __property Activex::TOleEnum GridStyle={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=22 };
  __property bool CanDrawLink={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=31 };
  __property bool AdjustOrg={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=9 };
  __property Graphics::TColor DrawColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=28 };
  __property bool AdjustDst={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=10 };
  __property bool Transparent={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=27 };
  __property bool CanStretchLink={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=33 };
  __property bool CanSizeNode={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=32 };
  __property bool Rigid={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=8 };
  __property bool AllowArrowKeys={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=7 };
  __property bool CanUndoRedo={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=41 };
  __property Activex::TOleEnum LinkingHandleSize={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=40 };
  __property Activex::TOleEnum EditMode={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=37 };
  __property Activex::TOleEnum SelectionHandleSize={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=39 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afSelNodesPtr SelNodes={ read=get_SelNodes, stored=false };
__published:
  __property Activex::TOleEnum BackMode={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=96 };
  __property float yShadowOffset={ read=GetSingleProp, write=SetSingleProp, stored=false, index=95 };
  __property bool OrthogonalDynamic={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=11 };
  __property bool SnapToGrid={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=25 };
  __property bool ScrollTrack={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=6 };
  __property bool Hidden={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=26 };
  __property bool CanMultiLink={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=5 };
  __property Activex::TOleEnum Shadow={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=93 };
  __property float xShadowOffset={ read=GetSingleProp, write=SetSingleProp, stored=false, index=94 };
  __property Graphics::TColor ShadowColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=38 };
  __property bool OrientedText={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=43 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afPicturesPtr Pictures={ read=get_Pictures, stored=false };
__published:
  __property bool CanChangeDst={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=19 };
  __property int MaxInDegree={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=44 };
  __property Activex::TOleEnum ShowPropertyPages={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=12 };
  __property int MaxOutDegree={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=45 };
  __property int MaxDegree={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=46 };
  __property bool OwnerDraw={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=115 };
  __property bool LinkOwnerDraw={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=117 };
  __property Graphics::TColor GradientColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=55 };
  __property Activex::TOleEnum Gradient={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=120 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afNodePtr RedoNode={ read=get_RedoNode, stored=false };
__published:
  __property bool NodeOwnerDraw={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=116 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afLinkPtr RedoLink={ read=get_RedoLink, stored=false };
__published:
public:  /* !__published] */
  __property Addflow5lib_tlb::afLinkPtr UndoLink={ read=get_UndoLink, stored=false };
__published:
  __property Activex::TOleEnum DrawMethod={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=98 };
  __property bool LogicalOnly={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=13 };
  __property Activex::TOleEnum SizeArrowMid={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=105 };
  __property bool CanFireError={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=17 };
  __property Activex::TOleEnum CycleMode={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=47 };
  __property Activex::TOleEnum SizeArrowDst={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=103 };
  __property Activex::TOleEnum SizeArrowOrg={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=104 };
  __property Activex::TOleEnum ShowJump={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=48 };
  __property bool CanChangeOrg={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=18 };
  __property Activex::TOleEnum RedoCode={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=101 };
  __property bool NoPrefix={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=99 };
  __property Activex::TOleEnum Ellipsis={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=97 };
  __property Activex::TOleEnum UndoCode={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=100 };
  __property bool ZeroOriginForExport={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=16 };
  __property bool ScrollWheel={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=14 };
  __property Activex::TOleEnum RemovePointAngle={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=15 };
  __property int PictureIndex={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=119 };
  __property Activex::TOleEnum MousePointer={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=70 };
public:  /* !__published] */
  __property Graphics::TPicture * MouseIcon={ read=GetTPictureProp, write=SetTPictureProp, stored=false, index=71 };
__published:
public:  /* !__published] */
  __property Addflow5lib_tlb::afNodesPtr Nodes={ read=get_Nodes, stored=false };
__published:
  __property Activex::TOleEnum BorderStyle={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=-504 };
  __property Activex::TOleEnum LastUserAction={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=76 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afNodePtr SelectedNode={ read=get_SelectedNode, stored=false };
__published:
  __property float DrawWidth={ read=GetSingleProp, write=SetSingleProp, stored=false, index=77 };
  __property Activex::TOleEnum ArrowDst={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=67 };
  __property float yExtent={ read=GetSingleProp, write=SetSingleProp, stored=false, index=84 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afNodePtr PointedNode={ read=get_PointedNode, stored=false };
__published:
public:  /* !__published] */
  __property Addflow5lib_tlb::afLinkPtr SelectedLink={ read=get_SelectedLink, stored=false };
__published:
  __property bool ShowToolTip={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=20 };
  __property bool CanReflexLink={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=4 };
  __property Activex::TOleEnum Appearance={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=-520 };
  __property float xExtent={ read=GetSingleProp, write=SetSingleProp, stored=false, index=83 };
  __property int xZoom={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=74 };
  __property bool RoundedCorner={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=49 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afCustomShapesPtr CustomShapes={ read=get_CustomShapes, stored=false };
__published:
  __property bool SkipUndo={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=107 };
  __property Activex::TOleEnum RoundedCornerSize={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=109 };
  __property Activex::TOleEnum EditHardReturn={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=54 };
  __property int CustomShapeIndex={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=118 };
  __property Activex::TOleEnum JumpSize={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=108 };
  __property System::WideString License={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=110 };
  __property Activex::TOleEnum RouteStartMethod={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=51 };
  __property int UndoSize={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=42 };
  __property int yZoom={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=75 };
  __property bool Autorouting={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=50 };
  __property int RouteMinDistance={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=53 };
public:  /* !__published] */
  __property Addflow5lib_tlb::afNodePtr UndoNode={ read=get_UndoNode, stored=false };
__published:
  __property int RouteGrain={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=52 };

  // OCX Events
  //
  __property TAddFlowError OnError={ read=FOnError, write=FOnError };
  __property TNotifyEvent OnScroll={ read=FOnScroll, write=FOnScroll };
  __property TNotifyEvent OnafLostFocus={ read=FOnafLostFocus, write=FOnafLostFocus };
  __property TNotifyEvent OnafGotFocus={ read=FOnafGotFocus, write=FOnafGotFocus };
  __property TAddFlowAfterAddNode OnAfterAddNode={ read=FOnAfterAddNode, write=FOnAfterAddNode };
  __property TAddFlowAfterAddLink OnAfterAddLink={ read=FOnAfterAddLink, write=FOnAfterAddLink };
  __property TAddFlowBeforeAddNode OnBeforeAddNode={ read=FOnBeforeAddNode, write=FOnBeforeAddNode };
  __property TAddFlowBeforeAddLink OnBeforeAddLink={ read=FOnBeforeAddLink, write=FOnBeforeAddLink };
  __property TNotifyEvent OnAfterResize={ read=FOnAfterResize, write=FOnAfterResize };
  __property TNotifyEvent OnAfterMove={ read=FOnAfterMove, write=FOnAfterMove };
  __property TNotifyEvent OnAfterStretch={ read=FOnAfterStretch, write=FOnAfterStretch };
  __property TNotifyEvent OnAfterSelect={ read=FOnAfterSelect, write=FOnAfterSelect };
  __property TAddFlowBeforeEdit OnBeforeEdit={ read=FOnBeforeEdit, write=FOnBeforeEdit };
  __property TAddFlowAfterEdit OnAfterEdit={ read=FOnAfterEdit, write=FOnAfterEdit };
  __property TAddFlowBeforeChangeDst OnBeforeChangeDst={ read=FOnBeforeChangeDst, write=FOnBeforeChangeDst };
  __property TAddFlowBeforeChangeOrg OnBeforeChangeOrg={ read=FOnBeforeChangeOrg, write=FOnBeforeChangeOrg };
  __property TAddFlowNodeOwnerDraw OnNodeOwnerDraw={ read=FOnNodeOwnerDraw, write=FOnNodeOwnerDraw };
  __property TAddFlowLinkOwnerDraw OnLinkOwnerDraw={ read=FOnLinkOwnerDraw, write=FOnLinkOwnerDraw };
  __property TAddFlowDiagramOwnerDraw OnDiagramOwnerDraw={ read=FOnDiagramOwnerDraw, write=FOnDiagramOwnerDraw };
};
typedef TAddFlow  TAddFlowProxy;

};     // namespace Addflow5lib_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Addflow5lib_tlb;
#endif

#pragma option pop

#endif // AddFlow5Lib_OCXH
